name: scipio-s3-storage

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  Tests:
    strategy:
      matrix:
        xcode_version:
          - "16.2" # 6.0
          # Comment out this once it's available
          # - "16.3" # 6.1
    env: 
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer"
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: SwiftLint
      run: swiftlint --strict
    - name: Run Tests
      run: |
        swift test --verbose
